### ISSUE TITLE
Another implementation 

### ISSUE THREAD

**Issue by gedw99** [paralin/go-indexeddb#1]
Just found yours by accident when searching for a golang implementation of an indexeddb system that runs on desktop and mobile . If you can advice about that it would be great .

here is another developers implementation if what your repo does . Maybe it’s interesting for you.

https://github.com/hack-pad/hackpadfs

Ultimately the reason for all this is because I am looking to get a dB for gioui that works on wasm browser, desktop and mobile. I am finding gioui to be highly productive and to produce high quality gui ux for end users. 

If your curious just ask

**Comment by paralin** [comment]
Hey, looks interesting. This package is a direct binding to IndexedDb, I have other abstractions on top of it in other projects.

For example I also have an implementation of unixfs and other data structures which map to indexeddb.

Thanks for the tip on the other package too, looks useful.
