### ISSUE TITLE
DurableObjectStore Count method is not implemented correctly

### ISSUE THREAD

**Issue by danielvladco** [paralin/go-indexeddb#9]
Hello, I came across an issue while using this library

The `Count()` method always returns 0 this is because on this line https://github.com/paralin/go-indexeddb/blob/master/durable.go#L314 it returns yearly and never actually calls `stor.Count(query)` and updates the count.

This is an easy fix, if you agree that this needs to be changed I can create a PR tomorrow.

Thanks for your work!

**Comment by paralin** [comment]
Thanks! I also notice in the heap profiler that there are a lot of IDBObjectStore objects leaking for some reason. If you manage to find a fix for that please let me know.
